spring:
  profiles:
    active: local
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #按驼峰命名规则自动匹配到实体类上,不需要用别名
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.ordin.model

---
spring:
   profiles: local
   thymeleaf:
     cache: false
   mvc:
     favicon:
        enabled: false   #网站默认图标
   datasource:          #数据源
     url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
     username: root
     password: admin1234
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
     dbcp2:
        test-on-borrow: true
        test-while-idle: true
        time-between-eviction-runs-millis: 3600000
        min-evictable-idle-time-millis: 300000
        remove-abandoned-on-borrow: true
        remove-abandoned-timeout: 1800
        max-wait-millis: 60000
        initial-size: 5
        min-idle: 5
        max-idle: 20
        max-total: 20
server:
  port: 8088
logging:
  file: /Users/guangcai.ji/work/output/blog/log/site.log
blog:   #自定义属性
  filePath: /Users/guangcai.ji/work/output/blog/upload/
  database: blog
  mysqlExec: /usr/local/bin/mysqldump -uroot -padmin1234 blog
  backupPath: /Users/guangcai.ji/work/output/blog/backup/
---
spring:
   profiles: prod
   thymeleaf:
     cache: false
   mvc:
       favicon:
         enabled: false
   datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
       username: root
       password: admin1234
       initialSize: 1
       minIdle: 3
       maxActive: 20
       # 配置获取连接等待超时的时间
       maxWait: 60000
       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       timeBetweenEvictionRunsMillis: 60000
       # 配置一个连接在池中最小生存的时间，单位是毫秒
       minEvictableIdleTimeMillis: 30000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false

server:
  port: 8088
logging:
  file: /home/admin/blog/output/log/site.log
blog:   #自定义属性
  #图片文件存储路径
  filePath: /home/admin/blog/files/
  #数据库名称
  database: blog
  #MYSQL 登录的命令行 /usr/bin/mysqldump -u 用户名 -p 密码（前面路径代表绝对路径）
  mysqlExec: /usr/bin/mysqldump -uroot -padmin1234 blog
  #数据库备份文件路径
  backupPath: /home/admin/blog/backup/